# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Wed Jun  7 10:25:38 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(961, 649)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 961, 600))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.sheet = QtGui.QWidget()
        self.sheet.setObjectName(_fromUtf8("sheet"))
        self.music_location_in_sheet = QtGui.QLineEdit(self.sheet)
        self.music_location_in_sheet.setGeometry(QtCore.QRect(110, 20, 501, 27))
        self.music_location_in_sheet.setObjectName(_fromUtf8("music_location_in_sheet"))
        self.label = QtGui.QLabel(self.sheet)
        self.label.setGeometry(QtCore.QRect(13, 20, 91, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.selected_meusic_in_sheet = QtGui.QToolButton(self.sheet)
        self.selected_meusic_in_sheet.setGeometry(QtCore.QRect(620, 20, 23, 25))
        self.selected_meusic_in_sheet.setObjectName(_fromUtf8("selected_meusic_in_sheet"))
        self.startButtonInSheet = QtGui.QPushButton(self.sheet)
        self.startButtonInSheet.setGeometry(QtCore.QRect(670, 20, 98, 27))
        self.startButtonInSheet.setObjectName(_fromUtf8("startButtonInSheet"))
        self.label_4 = QtGui.QLabel(self.sheet)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 891, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.after_music_info = QtGui.QTextBrowser(self.sheet)
        self.after_music_info.setGeometry(QtCore.QRect(20, 380, 401, 161))
        self.after_music_info.setObjectName(_fromUtf8("after_music_info"))
        self.label_5 = QtGui.QLabel(self.sheet)
        self.label_5.setGeometry(QtCore.QRect(30, 340, 951, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.clear_result_A = QtGui.QPushButton(self.sheet)
        self.clear_result_A.setGeometry(QtCore.QRect(780, 20, 98, 27))
        self.clear_result_A.setObjectName(_fromUtf8("clear_result_A"))
        self.after_music_info_2 = QtGui.QTextBrowser(self.sheet)
        self.after_music_info_2.setGeometry(QtCore.QRect(510, 380, 401, 161))
        self.after_music_info_2.setObjectName(_fromUtf8("after_music_info_2"))
        self.startButtonInSheet_frames = QtGui.QPushButton(self.sheet)
        self.startButtonInSheet_frames.setEnabled(False)
        self.startButtonInSheet_frames.setGeometry(QtCore.QRect(80, 300, 161, 27))
        self.startButtonInSheet_frames.setObjectName(_fromUtf8("startButtonInSheet_frames"))
        self.startButtonInSheet_datu2 = QtGui.QPushButton(self.sheet)
        self.startButtonInSheet_datu2.setEnabled(False)
        self.startButtonInSheet_datu2.setGeometry(QtCore.QRect(400, 300, 121, 27))
        self.startButtonInSheet_datu2.setObjectName(_fromUtf8("startButtonInSheet_datu2"))
        self.startButtonInSheet_datu3 = QtGui.QPushButton(self.sheet)
        self.startButtonInSheet_datu3.setEnabled(False)
        self.startButtonInSheet_datu3.setGeometry(QtCore.QRect(710, 300, 111, 27))
        self.startButtonInSheet_datu3.setObjectName(_fromUtf8("startButtonInSheet_datu3"))
        self.frames = QtGui.QLabel(self.sheet)
        self.frames.setGeometry(QtCore.QRect(50, 120, 241, 171))
        self.frames.setText(_fromUtf8(""))
        self.frames.setObjectName(_fromUtf8("frames"))
        self.hz = QtGui.QLabel(self.sheet)
        self.hz.setGeometry(QtCore.QRect(330, 120, 241, 171))
        self.hz.setText(_fromUtf8(""))
        self.hz.setObjectName(_fromUtf8("hz"))
        self.energy_in_sheet = QtGui.QLabel(self.sheet)
        self.energy_in_sheet.setGeometry(QtCore.QRect(640, 120, 241, 171))
        self.energy_in_sheet.setText(_fromUtf8(""))
        self.energy_in_sheet.setObjectName(_fromUtf8("energy_in_sheet"))
        self.tabWidget.addTab(self.sheet, _fromUtf8(""))
        self.info = QtGui.QWidget()
        self.info.setObjectName(_fromUtf8("info"))
        self.music_location_in_musicinfo = QtGui.QLineEdit(self.info)
        self.music_location_in_musicinfo.setGeometry(QtCore.QRect(110, 40, 501, 27))
        self.music_location_in_musicinfo.setObjectName(_fromUtf8("music_location_in_musicinfo"))
        self.selected_music_in_musicinfo = QtGui.QToolButton(self.info)
        self.selected_music_in_musicinfo.setGeometry(QtCore.QRect(620, 40, 23, 25))
        self.selected_music_in_musicinfo.setObjectName(_fromUtf8("selected_music_in_musicinfo"))
        self.label_2 = QtGui.QLabel(self.info)
        self.label_2.setGeometry(QtCore.QRect(13, 40, 91, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.startButtonInMusicInfo = QtGui.QPushButton(self.info)
        self.startButtonInMusicInfo.setGeometry(QtCore.QRect(670, 40, 98, 27))
        self.startButtonInMusicInfo.setObjectName(_fromUtf8("startButtonInMusicInfo"))
        self.startButtonInMusicInfo_mfcc = QtGui.QPushButton(self.info)
        self.startButtonInMusicInfo_mfcc.setEnabled(False)
        self.startButtonInMusicInfo_mfcc.setGeometry(QtCore.QRect(60, 260, 131, 27))
        self.startButtonInMusicInfo_mfcc.setCheckable(False)
        self.startButtonInMusicInfo_mfcc.setChecked(False)
        self.startButtonInMusicInfo_mfcc.setDefault(False)
        self.startButtonInMusicInfo_mfcc.setObjectName(_fromUtf8("startButtonInMusicInfo_mfcc"))
        self.startButtonInMusicInfo_lpc = QtGui.QPushButton(self.info)
        self.startButtonInMusicInfo_lpc.setEnabled(False)
        self.startButtonInMusicInfo_lpc.setGeometry(QtCore.QRect(300, 260, 121, 27))
        self.startButtonInMusicInfo_lpc.setObjectName(_fromUtf8("startButtonInMusicInfo_lpc"))
        self.startButtonInMusicInfo_mfcc_d1 = QtGui.QPushButton(self.info)
        self.startButtonInMusicInfo_mfcc_d1.setEnabled(False)
        self.startButtonInMusicInfo_mfcc_d1.setGeometry(QtCore.QRect(520, 260, 141, 27))
        self.startButtonInMusicInfo_mfcc_d1.setObjectName(_fromUtf8("startButtonInMusicInfo_mfcc_d1"))
        self.startButtonInMusicInfo_sharpness = QtGui.QPushButton(self.info)
        self.startButtonInMusicInfo_sharpness.setEnabled(False)
        self.startButtonInMusicInfo_sharpness.setGeometry(QtCore.QRect(750, 260, 141, 27))
        self.startButtonInMusicInfo_sharpness.setObjectName(_fromUtf8("startButtonInMusicInfo_sharpness"))
        self.startButtonInMusicInfo_zcr = QtGui.QPushButton(self.info)
        self.startButtonInMusicInfo_zcr.setEnabled(False)
        self.startButtonInMusicInfo_zcr.setGeometry(QtCore.QRect(50, 480, 151, 27))
        self.startButtonInMusicInfo_zcr.setObjectName(_fromUtf8("startButtonInMusicInfo_zcr"))
        self.startButtonInMusicInfo_energy = QtGui.QPushButton(self.info)
        self.startButtonInMusicInfo_energy.setEnabled(False)
        self.startButtonInMusicInfo_energy.setGeometry(QtCore.QRect(300, 480, 141, 27))
        self.startButtonInMusicInfo_energy.setObjectName(_fromUtf8("startButtonInMusicInfo_energy"))
        self.startButtonInMusicInfo_spectralrolloff = QtGui.QPushButton(self.info)
        self.startButtonInMusicInfo_spectralrolloff.setEnabled(False)
        self.startButtonInMusicInfo_spectralrolloff.setGeometry(QtCore.QRect(510, 480, 161, 27))
        self.startButtonInMusicInfo_spectralrolloff.setObjectName(_fromUtf8("startButtonInMusicInfo_spectralrolloff"))
        self.startButtonInMusicInfo_spectralflatness = QtGui.QPushButton(self.info)
        self.startButtonInMusicInfo_spectralflatness.setEnabled(False)
        self.startButtonInMusicInfo_spectralflatness.setGeometry(QtCore.QRect(730, 480, 181, 27))
        self.startButtonInMusicInfo_spectralflatness.setObjectName(_fromUtf8("startButtonInMusicInfo_spectralflatness"))
        self.mfcc = QtGui.QLabel(self.info)
        self.mfcc.setGeometry(QtCore.QRect(40, 130, 191, 121))
        self.mfcc.setText(_fromUtf8(""))
        self.mfcc.setObjectName(_fromUtf8("mfcc"))
        self.lpc = QtGui.QLabel(self.info)
        self.lpc.setGeometry(QtCore.QRect(270, 130, 191, 121))
        self.lpc.setText(_fromUtf8(""))
        self.lpc.setObjectName(_fromUtf8("lpc"))
        self.mfcc_d1 = QtGui.QLabel(self.info)
        self.mfcc_d1.setGeometry(QtCore.QRect(490, 130, 191, 121))
        self.mfcc_d1.setText(_fromUtf8(""))
        self.mfcc_d1.setObjectName(_fromUtf8("mfcc_d1"))
        self.sharpness = QtGui.QLabel(self.info)
        self.sharpness.setGeometry(QtCore.QRect(730, 130, 191, 121))
        self.sharpness.setText(_fromUtf8(""))
        self.sharpness.setObjectName(_fromUtf8("sharpness"))
        self.zcr = QtGui.QLabel(self.info)
        self.zcr.setGeometry(QtCore.QRect(30, 350, 191, 121))
        self.zcr.setText(_fromUtf8(""))
        self.zcr.setObjectName(_fromUtf8("zcr"))
        self.energy = QtGui.QLabel(self.info)
        self.energy.setGeometry(QtCore.QRect(280, 350, 191, 121))
        self.energy.setText(_fromUtf8(""))
        self.energy.setObjectName(_fromUtf8("energy"))
        self.spectralrolloff = QtGui.QLabel(self.info)
        self.spectralrolloff.setGeometry(QtCore.QRect(500, 350, 191, 121))
        self.spectralrolloff.setText(_fromUtf8(""))
        self.spectralrolloff.setObjectName(_fromUtf8("spectralrolloff"))
        self.spectralflatness = QtGui.QLabel(self.info)
        self.spectralflatness.setGeometry(QtCore.QRect(720, 350, 191, 121))
        self.spectralflatness.setText(_fromUtf8(""))
        self.spectralflatness.setObjectName(_fromUtf8("spectralflatness"))
        self.tabWidget.addTab(self.info, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.exit = QtGui.QAction(MainWindow)
        self.exit.setObjectName(_fromUtf8("exit"))
        self.menu.addAction(self.exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "民族音乐信息提取系统", None))
        self.label.setText(_translate("MainWindow", "音乐文件路径", None))
        self.selected_meusic_in_sheet.setText(_translate("MainWindow", "...", None))
        self.startButtonInSheet.setText(_translate("MainWindow", "开始提取", None))
        self.label_4.setText(_translate("MainWindow", "提取中间信息展示： ----------------------------------------------------------------------------------------------------------------------------------------------", None))
        self.label_5.setText(_translate("MainWindow", "最后结果展示： --------------------------------------------------------------------------------------------------------------------------------------------------", None))
        self.clear_result_A.setText(_translate("MainWindow", "清除结果", None))
        self.startButtonInSheet_frames.setText(_translate("MainWindow", "显示音乐波形图大图", None))
        self.startButtonInSheet_datu2.setText(_translate("MainWindow", "显示频率大图", None))
        self.startButtonInSheet_datu3.setText(_translate("MainWindow", "显示能量大图", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sheet), _translate("MainWindow", "乐谱", None))
        self.selected_music_in_musicinfo.setText(_translate("MainWindow", "...", None))
        self.label_2.setText(_translate("MainWindow", "音乐文件路径", None))
        self.startButtonInMusicInfo.setText(_translate("MainWindow", "开始提取", None))
        self.startButtonInMusicInfo_mfcc.setText(_translate("MainWindow", "显示MFCC大图", None))
        self.startButtonInMusicInfo_lpc.setText(_translate("MainWindow", "显示LPC大图", None))
        self.startButtonInMusicInfo_mfcc_d1.setText(_translate("MainWindow", "显示MFCC_D1大图", None))
        self.startButtonInMusicInfo_sharpness.setText(_translate("MainWindow", "显示sharpness大图", None))
        self.startButtonInMusicInfo_zcr.setText(_translate("MainWindow", "显示zcr大图", None))
        self.startButtonInMusicInfo_energy.setText(_translate("MainWindow", "显示energy大图", None))
        self.startButtonInMusicInfo_spectralrolloff.setText(_translate("MainWindow", "显示spectralrolloff大图", None))
        self.startButtonInMusicInfo_spectralflatness.setText(_translate("MainWindow", "显示spectralflatness大图", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info), _translate("MainWindow", "音乐信息", None))
        self.menu.setTitle(_translate("MainWindow", "菜单", None))
        self.exit.setText(_translate("MainWindow", "退出", None))

